set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to clk
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to done_filt_ff
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to rst_sync
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_R[7]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_R[6]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_R[5]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_R[4]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_R[3]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_R[2]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_R[1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_R[0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_G[7]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_G[6]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_G[5]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_G[4]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_G[3]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_G[2]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_G[1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_G[0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_B[7]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_B[6]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_B[5]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_B[4]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_B[3]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_B[2]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_B[1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_B[0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_HS
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_VS
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg1[7]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg1[6]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg1[5]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg1[4]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg1[3]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg1[2]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg1[1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg1[0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg2[0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg2[1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg2[2]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg2[3]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg2[4]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg2[5]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg2[6]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg2[7]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg3[0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg3[1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg3[2]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg3[3]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg3[4]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg3[5]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg3[6]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg3[7]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg4[0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg4[1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg4[2]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg4[3]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg4[4]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg4[5]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg4[6]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg4[7]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg5[0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg5[1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg5[2]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg5[3]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg5[4]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg5[5]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg5[6]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg5[7]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg6[0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg6[1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg6[2]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg6[3]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg6[4]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg6[5]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg6[6]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg6[7]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_BLANK_N
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_SYNC_N
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_CLK

set_location_assignment PIN_AF14 -to clk
set_location_assignment PIN_V16 -to done_filt_ff
set_location_assignment PIN_AB12 -to rst_sync
set_location_assignment PIN_F13 -to VGA_R[7]
set_location_assignment PIN_E12 -to VGA_R[6]
set_location_assignment PIN_D12 -to VGA_R[5]
set_location_assignment PIN_C12 -to VGA_R[4]
set_location_assignment PIN_B12 -to VGA_R[3]
set_location_assignment PIN_E13 -to VGA_R[2]
set_location_assignment PIN_C13 -to VGA_R[1]
set_location_assignment PIN_A13 -to VGA_R[0]
set_location_assignment PIN_E11 -to VGA_G[7]
set_location_assignment PIN_F11 -to VGA_G[6]
set_location_assignment PIN_G12 -to VGA_G[5]
set_location_assignment PIN_G11 -to VGA_G[4]
set_location_assignment PIN_G10 -to VGA_G[3]
set_location_assignment PIN_H12 -to VGA_G[2]
set_location_assignment PIN_J10 -to VGA_G[1]
set_location_assignment PIN_J9  -to VGA_G[0]
set_location_assignment PIN_J14 -to VGA_B[7]
set_location_assignment PIN_G15 -to VGA_B[6]
set_location_assignment PIN_F15 -to VGA_B[5]
set_location_assignment PIN_H14 -to VGA_B[4]
set_location_assignment PIN_F14 -to VGA_B[3]
set_location_assignment PIN_H13 -to VGA_B[2]
set_location_assignment PIN_G13 -to VGA_B[1]
set_location_assignment PIN_B13 -to VGA_B[0]
set_location_assignment PIN_B11 -to VGA_HS
set_location_assignment PIN_D11 -to VGA_VS
set_location_assignment PIN_F10 -to VGA_BLANK_N
set_location_assignment PIN_C10 -to VGA_SYNC_N
set_location_assignment PIN_A11 -to VGA_CLK
set_location_assignment PIN_AH28 -to seg1[6]
set_location_assignment PIN_AG28 -to seg1[5]
set_location_assignment PIN_AF28 -to seg1[4]
set_location_assignment PIN_AG27 -to seg1[3]
set_location_assignment PIN_AE28 -to seg1[2]
set_location_assignment PIN_AE27 -to seg1[1]
set_location_assignment PIN_AE26 -to seg1[0]
set_location_assignment PIN_AJ29 -to seg2[0]
set_location_assignment PIN_AH29 -to seg2[1]
set_location_assignment PIN_AH30 -to seg2[2]
set_location_assignment PIN_AG30 -to seg2[3]
set_location_assignment PIN_AF29 -to seg2[4]
set_location_assignment PIN_AF30 -to seg2[5]
set_location_assignment PIN_AD27 -to seg2[6]
set_location_assignment PIN_AB23 -to seg3[0]
set_location_assignment PIN_AE29 -to seg3[1]
set_location_assignment PIN_AD29 -to seg3[2]
set_location_assignment PIN_AC28 -to seg3[3]
set_location_assignment PIN_AD30 -to seg3[4]
set_location_assignment PIN_AC29 -to seg3[5]
set_location_assignment PIN_AC30 -to seg3[6]
set_location_assignment PIN_AD26 -to seg4[0]
set_location_assignment PIN_AC27 -to seg4[1]
set_location_assignment PIN_AD25 -to seg4[2]
set_location_assignment PIN_AC25 -to seg4[3]
set_location_assignment PIN_AB28 -to seg4[4]
set_location_assignment PIN_AB25 -to seg4[5]
set_location_assignment PIN_AB22 -to seg4[6]
set_location_assignment PIN_AA24 -to seg5[0]
set_location_assignment PIN_Y23  -to seg5[1]
set_location_assignment PIN_Y24  -to seg5[2]
set_location_assignment PIN_W22  -to seg5[3]
set_location_assignment PIN_W24  -to seg5[4]
set_location_assignment PIN_V23  -to seg5[5]
set_location_assignment PIN_W25  -to seg5[6]
set_location_assignment PIN_V25  -to seg6[0]
set_location_assignment PIN_AA28 -to seg6[1]
set_location_assignment PIN_Y27  -to seg6[2]
set_location_assignment PIN_AB27 -to seg6[3]
set_location_assignment PIN_AB26 -to seg6[4]
set_location_assignment PIN_AA26 -to seg6[5]
set_location_assignment PIN_AA25 -to seg6[6]

