set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to clk
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to done_filt_ff
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to rst_sync
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_R[3]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_R[2]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_R[1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_R[0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_G[3]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_G[2]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_G[1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_G[0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_B[3]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_B[2]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_B[1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_B[0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_HS
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to VGA_VS
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg1[7]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg1[6]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg1[5]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg1[4]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg1[3]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg1[2]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg1[1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg1[0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg2[0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg2[1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg2[2]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg2[3]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg2[4]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg2[5]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg2[6]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg2[7]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg3[0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg3[1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg3[2]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg3[3]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg3[4]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg3[5]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg3[6]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg3[7]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg4[0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg4[1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg4[2]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg4[3]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg4[4]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg4[5]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg4[6]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg4[7]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg5[0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg5[1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg5[2]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg5[3]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg5[4]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg5[5]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg5[6]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg5[7]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg6[0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg6[1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg6[2]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg6[3]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg6[4]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg6[5]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg6[6]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to seg6[7]

set_location_assignment PIN_P11 -to clk
set_location_assignment PIN_A8 -to done_filt_ff
set_location_assignment PIN_C10 -to rst_sync
set_location_assignment PIN_AA1 -to VGA_R[3]
set_location_assignment PIN_V1 -to VGA_R[2]
set_location_assignment PIN_Y2 -to VGA_R[1]
set_location_assignment PIN_Y1 -to VGA_R[0]
set_location_assignment PIN_W1 -to VGA_G[3]
set_location_assignment PIN_T2 -to VGA_G[2]
set_location_assignment PIN_R2 -to VGA_G[1]
set_location_assignment PIN_R1 -to VGA_G[0]
set_location_assignment PIN_P1 -to VGA_B[3]
set_location_assignment PIN_T1 -to VGA_B[2]
set_location_assignment PIN_P4 -to VGA_B[1]
set_location_assignment PIN_N2 -to VGA_B[0]
set_location_assignment PIN_N3 -to VGA_HS
set_location_assignment PIN_N1 -to VGA_VS
set_location_assignment PIN_D15 -to seg1[7]
set_location_assignment PIN_C17 -to seg1[6]
set_location_assignment PIN_D17 -to seg1[5]
set_location_assignment PIN_E16 -to seg1[4]
set_location_assignment PIN_C16 -to seg1[3]
set_location_assignment PIN_C15 -to seg1[2]
set_location_assignment PIN_E15 -to seg1[1]
set_location_assignment PIN_C14 -to seg1[0]
set_location_assignment PIN_C18 -to seg2[0]
set_location_assignment PIN_D18 -to seg2[1]
set_location_assignment PIN_E18 -to seg2[2]
set_location_assignment PIN_B16 -to seg2[3]
set_location_assignment PIN_A17 -to seg2[4]
set_location_assignment PIN_A18 -to seg2[5]
set_location_assignment PIN_B17 -to seg2[6]
set_location_assignment PIN_A16 -to seg2[7]
set_location_assignment PIN_B20 -to seg3[0]
set_location_assignment PIN_A20 -to seg3[1]
set_location_assignment PIN_B19 -to seg3[2]
set_location_assignment PIN_A21 -to seg3[3]
set_location_assignment PIN_B21 -to seg3[4]
set_location_assignment PIN_C22 -to seg3[5]
set_location_assignment PIN_B22 -to seg3[6]
set_location_assignment PIN_A19 -to seg3[7]
set_location_assignment PIN_F21 -to seg4[0]
set_location_assignment PIN_E22 -to seg4[1]
set_location_assignment PIN_E21 -to seg4[2]
set_location_assignment PIN_C19 -to seg4[3]
set_location_assignment PIN_C20 -to seg4[4]
set_location_assignment PIN_D19 -to seg4[5]
set_location_assignment PIN_E17 -to seg4[6]
set_location_assignment PIN_D22 -to seg4[7]
set_location_assignment PIN_F18 -to seg5[0]
set_location_assignment PIN_E20 -to seg5[1]
set_location_assignment PIN_E19 -to seg5[2]
set_location_assignment PIN_J18 -to seg5[3]
set_location_assignment PIN_H19 -to seg5[4]
set_location_assignment PIN_F19 -to seg5[5]
set_location_assignment PIN_F20 -to seg5[6]
set_location_assignment PIN_F17 -to seg5[7]
set_location_assignment PIN_J20 -to seg6[0]
set_location_assignment PIN_K20 -to seg6[1]
set_location_assignment PIN_L18 -to seg6[2]
set_location_assignment PIN_N18 -to seg6[3]
set_location_assignment PIN_M20 -to seg6[4]
set_location_assignment PIN_N19 -to seg6[5]
set_location_assignment PIN_N20 -to seg6[6]
set_location_assignment PIN_L19 -to seg6[7]

